sahib/rmlint

SConstruct

- Do not raise an error if an environment variable isn't defined (notably: `TERM` should be optional).
- Forward the `PKG_CONFIG_PATH` variable, used by `pkg-config`.
Rationale: I'm packaging `rmlint` for [nix](https://github.com/NixOS/nixpkgs).

Updated the way environment is forwarded to scons.

---

SConstruct

Build systems like autoconf and friends respect `$PKG_CONFIG` being set to a different binary path other than just 'pkg-config', which is useful when cross-compiling; we should respect that.

Respect $PKG_CONFIG

---

lib/cmdline.c

I suppose with_color should have non-zero value if with_stdout_color or
with_stderr_color is non-zero. Former one was not used due to typo.
Issue detected by Cppcheck:
[lib/cmdline.c:1220] -> [lib/cmdline.c:1220]: (style) Same expression on both sides of '|'.

lib: Fix typo in with_color assignment

---

docs/install.rst

Space between "install" and "libelf-dev" did not exist in Ubuntu dependencies block.

Minor spelling correction

---

lib/utilities.c

I got compile error on FreeBSD clang version 3.4.1/FreeBSD 10.1.
```
Compiling ==> lib/utilities.c
lib/utilities.c:906:11: error: use of undeclared identifier 'partition'
(void)partition;
^
lib/utilities.c:856:55: warning: unused parameter 'dev' [-Wunused-parameter]
dev_t rm_mounts_get_disk_id(RmMountTable *self, dev_t dev, const char *path) {
^
1 warning and 1 error generated.
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sahib/rmlint/164)

Fix compile error when RM_MOUNTTABLE_IS_USABLE not defined

---

gui/shredder/views/locations.py

File "/usr/lib/python3.5/site-packages/shredder/views/locations.py", line 360, in add_entry
path = path.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
This patch fixes the bug by skipping volumes without path.

The gui breaks when a blank optical disc is in the drive as it doesn't have a path

---

gui/shredder/views/settings.py

Without this test, I have : an error:
15:50:40 ⚐ INFO     root:29: Starting up.
15:50:40 ⚐ INFO     application:102: Loading resources from: /usr/lib/python3.5/site-packages/shredder/resources/shredder.gresource
15:50:40 ⚙ DEBUG    application:144: Instancing views.
Traceback (most recent call last):
File "/usr/lib/python3.5/site-packages/shredder/application.py", line 145, in do_startup
self.win.views.add_view(SettingsView(self), 'settings')
File "/usr/lib/python3.5/site-packages/shredder/views/settings.py", line 164, in __init__
self.build()
File "/usr/lib/python3.5/site-packages/shredder/views/settings.py", line 296, in build
self.append_entry(*entry[1:])
File "/usr/lib/python3.5/site-packages/shredder/views/settings.py", line 239, in append_entry
'description': desc.lower() or '', …

Test for None

---

gui/shredder.desktop

Lintian requires that desktop files shipped with Debian packages have a Keywords entry. This is what I have added for now. Feel free to change it to ones you think are more appropriate.
Cheers.

Add keywords to desktop file.

---

lib/utilities.c

If scons sets HAVE_SYSMACROS_H to 0, that still counts as being defined.
So use #if instead of #ifdef.
Prevents build failure on macOS.

Use #if not #ifdef with HAVE_SYSMACROS_H

---

.gitignore
lib/formats/py.py

Improvements to python script

---

pkg/centos/rmlint.spec

This fixes 2 issues:
The download URL was incorrect:
```
warning: Downloading https://github.com/sahib/rmlint/archive/rmlint-2.6.1.tar.gz to /home/phemmer/rpmbuild/SOURCES/rmlint-2.6.1.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
error: Couldn't download https://github.com/sahib/rmlint/archive/rmlint-2.6.1.tar.gz
```
The shredder files weren't specified in the `%files` section:
```
error: Installed (but unpackaged) file(s) found:
/usr/lib/python3.4/site-packages/Shredder-2.6.1.Penetrating.Pineapple-py3.4.egg-info
/usr/lib/python3.4/site-packages/shredder/__init__.py
/usr/lib/python3.4/site-packages/shredder/__main__.py
/usr/lib/python3.4/site-packages/shredder/__pycache__/__init__.cpython-34.pyc
/usr/lib/python3.4/site-packages/shredder/__pycache__/__init__.cpython-34. …
```

fix centos7 spec URL & split shredder to new package

---

po/de.po

Fixes one typo in the german translation.

Typo in DE Translation

---

lib/formats/sh.sh

... which is broken due to incorrect quoting. My fix does correct the quoting issue introduced in aa9b063827da6903770a1d36debae71fb669d8a6. 
Also remove trailing spaces.
Please don't hesitate to ask any question or give me feedback on this.

Fix percentage in progress bar on rmlint.sh

---

docs/rmlint.1.rst

Restrucured code formatting to make line breaks visible.

Fix/doc: Fixed formatting in docs/rmlint.1.rst

---

SConstruct
lib/checksum.c
lib/cmdline.c
lib/config.h.in
lib/file.c
lib/formats.c
lib/formats/sh.c.in
lib/hasher.c
lib/md-scheduler.c
lib/pathtricia.c
lib/preprocess.c
lib/replay.c
lib/session.c
lib/shredder.c
lib/treemerge.c
lib/utilities.c
lib/xattr.c

This series fixes some issues that are causing compiler warnings, and it also potentially avoids some run-time bugs; one subtle bug could eventually arise if *all* debug assertions were elided, because its argument is not just a declaration of some condition, but rather an important call with side effects.
Here's a quick summary of the patches:
1. SConstruct: Use `-Wno-cast-function-type' only if GCC's major version >= 8
2. lib/session.c: dedupe: Format strings with `G_GINT64_FORMAT'
3. C: Fix up asserts
4. C: Remove the `rm_assert_gentle*()' macros

A quick clean up

---

SConstruct
lib/config.h.in
lib/session.c
lib/session.h
po/de.po
po/es.po
po/fr.po
po/rmlint.pot

This series cleans up and inlines the following functions:
* `rm_session_abort()`
* `rm_session_was_aborted()`
The warning messages produced by the latter (including the translations) have also undergone a minor cleanup with regard to punctuation and capitalization.
Also, this series introduces a portable means by which to force the compiler to inline a function.

Inline the abort functions

---

docs/translators.rst
po/SConscript
po/de.po
po/es.po
po/fr.po
po/rmlint.pot

This series implements the means by which `gettext` translation files can be updated with one command:
$ scons gettext
It also uses this new facility to update the `po/*.po[t]` files (however, no new translations are provided).

Update and ease support of gettext translations

---

lib/cmdline.c
lib/fts/fts.c
lib/fts/fts.h
lib/traverse.c
lib/treemerge.c
po/de.po
po/es.po
po/fr.po
po/rmlint.pot

This series mainly improves `rm_tm_count_files()` by removing an unnecessary parameter, avoiding re-calculation, and introducing [slightly more] graceful error handling. It may be helpful to consult the commit mesage in the following commit of the series:
* lib/treemerge.c: remove unnecessary parameter and recalculation of `path_count' (a5ef34b881d95e41b08ae5a91c92cb0d8cb47517)

Cleanup in treemerge

---

lib/cfg.h
lib/cmdline.c
lib/session.c
lib/treemerge.c
po/de.po
po/es.po
po/fr.po
po/rmlint.pot

This series documents and improves the usage of `RmCfg::path_count`, and then fixes a related programming mistake that manifests when mixing the aforementioned options. As an aside, the `gettext` files are also updated.

Forbid `--replay' with `--dedupe' or `--is-reflink'

---

tests/SConscript

Avoid confusing error message about nosetests not being found when
there is a test failure.

Fix nosetests search.

---

SConstruct
lib/checksums/metrohash128.c

When compiled with -msse4.2 optimisation applied across the board,
'rmlint -g' terminates with the SIGILL signal on pre-SSE4.2 platforms.
It seems like GCC 8.2.0 optimises the floor function/macro call from
lib/formats/progressbar.c with illegal instructions. With Clang, even
more such optimisations occur.
Use function attributes to enable SSE4.2 feature only where required,
so that both types of CPU are fully supported.

Fix support for pre-SSE4.2 CPUs.

---

lib/utilities.c

The `rm_offset_get_fiemap` function took a 32-bit signed integer describing the file offset; but the [kernel data structure is defined as a 64-bit unsigned integer](https://www.kernel.org/doc/Documentation/filesystems/fiemap.txt).  This caused rmlint to fail to read the fiemap for files larger than 2 GB.
In the process of debugging and fixing the issue; I ran into some compilation logs in the `_RM_OFFSET_DEBUG` logging, so I fixed those while I was at it.

Teach rmlint to detect reflinks with > 2GB files

---

lib/cmdline.c
po/de.po
po/es.po
po/fr.po
po/rmlint.pot

Other places in the documentation seem to use "mountpoint" instead of "mount point", so I left it as a single word.

Fix typo in command-line help

---

docs/tutorial.rst

Was -e, now -i in bash example code in the tutorial.

Tutorial: Correct option, dup files same basename

---

lib/xattr.c

without this check for HAVE_XATTR, build fails for systems that don't have sys/xattr.h
I'm working on a nice FreeBSD port and stumbled upon this.

added another check for HAVE_XATTR in xattr.c

---

docs/index.rst

Waffle no longer exists, see [Farewell from Waffle](https://web.archive.org/web/20190316131550/https://blog.waffle.io/farewell-from-waffle-%EF%B8%8F-794da4a72851?gi=2d1c6b4facf4).

Remove defunct Waffle badge

---

.format.sh
lib/formats/sh.sh

This fixes [shellcheck](https://shellcheck.net) linter errors and fixes a problem with how `iconv` is being invoked, which was referenced in the comments.
shellcheck's [SC2094](https://github.com/koalaman/shellcheck/wiki/SC2094) explains the problem with the code as it was.

Shellcheck cleanup

---

lib/formats/sh.sh

when DO_KEEP_DIR_TIMESTAMPS was not set the STAMPFILE was created but not removed

fix unnecessary STAMPFILE creation in rmlint.sh

---

lib/formats/json.c

Just ran:
`rmlint . -D -T minimaldirs`
and some of the JSON produced was broken, namely any time a 'part_of_directory' record was generated for a path that had something goofy like one double-quote in it, the 'path' field was escaped properly but the 'parent_path' field was not.  The 'path' field output is escaped via 'rm_fmt_json_key_unsafe', whereas the 'parent_path' field just uses 'rm_fmt_json_key'.  Probably both ought to use _unsafe.

Escape contents of 'parent_path' JSON field

---

SConstruct

fiemap does not depend on gettext.

Don't disable fiemap when gettext is disabled

---

gui/shredder/tree.py

There is a small typo in gui/shredder/tree.py.
Should read `convenience` rather than `convinience`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, convinience -> convenience

---

tests/test_formatters/test_sh.py

Before b9d328be2041e42813119d060c86893853b8e250 "-p" (aka paranoid mode) deleted files even if the original file differed from the (not anymore) duplicate.
This wasn't captured by the test due to the following reasons:
- the expected error message was included in rmlint's output
- Python's "open(..., 'w')" command creates the given file anew
To make sure that our file is still sane and sound, we need to reread it from the drive and survey its content.
----
To test this pull request, I've used `scons test` on `develop` on the current `HEAD` but also on the old `sh.sh` variant:
```sh
scons test # runs fine
cat > remove-check.patch << 'EOF'
diff --git a/lib/formats/sh.sh b/lib/formats/sh.sh
index b5e495d5..39ed3b99 100644
--- a/lib/formats/sh.sh
+++ b/lib/formats/sh.sh
@@ -160,7 +160,6 @@ …
```

test_formatter: sh: check whether file still exists

---

SConstruct

Otherwise ARGUMENTS.get('DEBUG') evaluated to `True` when actually `0` was passed

Fix print of config parameters

---

SConstruct

Hello,
While trying to package rmlint for the conda package manager, I came across the following issue: compiler paths and flags from `os.environ` are incorporated into the build environment after some checks (namely `CheckCC()`) execute. Therefore, if the default values of scons' CC etc. are non-functional (as in a cross-build environment where CC is named by host arch etc.), then these tests fail, aborting the build before paths to CC and CXX are read from environment variables. This simply shifts the block of code that overwrites scons' CC/CXX etc up before any checks are performed. The attached patch seems to allow successful compilation & install at least in Conda's build environment.
Best,
Kevin

Move all CC checks after setting CC/CXX vars

---

docs/rmlint.1.rst
docs/tutorial.rst
lib/cmdline.c
lib/logger.c
lib/reflink.c
po/de.po
po/es.po
po/fr.po
po/rmlint.pot
tests/test_formatters/test_others.py

Only five verbosity levels really exist (`-VV` through `-vv`), and `-VV` couldn't even be reached before - but that was masked by the first two (G_LOG_LEVEL_ERROR and G_LOG_LEVEL_CRITICAL) being the wrong way around.
This will only break scripts if they relied on `-V` silencing errors logged to stderr, but if scripts were silencing stderr they were most likely ignoring it, and this was an undocumented "feature" (the docs recommended `-VVV`), so IMO it's not a concern.
```
$ rmlint --is-reflink nothing nothing
```
Output before and after these changes:
```
ERROR: lib/utilities.c:1335: rm_util_link_type: Error opening nothing: No such file or directory
An error occurred during checking
```
```
$ rmlint --is-reflink -V nothing nothing
```
Output before these changes:
(no output)
The warning …

Fix verbosity logic and documentation

---

docs/rmlint.1.rst
lib/utilities.c
tests/test_mains/test_is_reflink.py

The most important change here is to allow rm_util_link_type to return RM_LINK_SYMLINK by checking for it earlier.
```
$ touch foo.txt bar.txt
$ ln -s bar.txt link.txt
$ rmlint --is-reflink foo.txt link.txt
```
Result before these changes: `Not a file` (exit status 3)
Result after these changes: `Encountered a symlink` (exit status 9)

--is-reflink and rm_util_link_type fixes

---

docs/rmlint.1.rst

Replace "Reading the manpages o these tools" by "Reading the manpages o**f** these tools"

Fix small typo on the manpage

---

docs/rmlint.1.rst

Double dashes are being interpreted as en dashes like `–algorithm` on https://rmlint.readthedocs.io/en/latest/rmlint.1.html

DOC: Fix formatting

---

docs/tutorial.rst

Clone maintains metadata of both files, while reflink deletes one and replaces it with a reflink.  See [What does a rmlint's “clone” for btrfs do?](https://unix.stackexchange.com/a/428253) on Unix StackExchange

DOC: Clarify clone vs reflink

---

tests/test_options/test_replay.py
tests/test_options/test_size.py
tests/test_options/test_stdin.py
tests/utils.py

Hi,
This fixes two things:
* tests couldn't run when `/tmp` isn't accessible
* `test_stdin.test_path_starting_with_dash` could fail because STDERR was captured and non-empty (because of #519)

Tests: stop using hardcoded /tmp, don't capture stderr

---

SConstruct
lib/config.h.in
lib/hasher.c
lib/md-scheduler.c
lib/traverse.c
lib/utilities.c

The worst of them were an undefined UINTPTR_MAX in RM_PLATFORM_*, which could both be false and caused a stat struct to be mis-casted in traverse.c, and a non-macro HASHER_FADVISE_FLAGS that made rm_hasher_request_readahead a no-op since commit 31cd32f1.
Also add a static assert in the usual ADD_FILE to make sure it never casts between incompatible stat structs, and -Werror=undef so we don't allow undefined macros to silently evaluate to zero.
The UINTPTR_MAX issue is a regression caused by 90edf021, which removed the inttypes.h include in config.h.in.
Fixes #549
---
Here's the preprocessor condition that wasn't working:
https://github.com/sahib/rmlint/blob/bdb591f4bc124fad6da1035ffb2b513826e9d64f/lib/traverse.c#L215
Here's the definition of RM_PLATFORM_32: …

fix undefined macros

---

lib/SConscript

This was causing issues on platforms that don't support SSE2, such as ARM.
Fixes #547

SConscript: fix copy-paste error

---

docs/SConscript
lib/cmdline.c

Hi,
Pre-compressing the manpage causes QA warnings on Gentoo (and could also be a problem on Debian, Fedora or Arch Linux, as a fellow Gentoo developer explains [in his blog](https://cmpct.info/~sam/blog/posts/automatic-manpage-compression/)).
It would be nice to disable this feature.

Do not compress manpage

---

lib/formats/sh.sh

To correct ShellCheck SC2086 (Double quote to prevent globbing and word splitting) in generated rmlint.sh.

Add "quotes" to $RMLINT_BINARY in clone() function

---

docs/install.rst

this link does not exist any more (404 http)
> https://raw.githubusercontent.com/Homebrew/install/master/install
resource:
> https://github.com/Homebrew/install/tree/master#install-homebrew-on-macos-or-linux

docs: MacOS: install brew update

---

SConstruct

with
```
header=
'#include<a>'
'#include<b>'
```
scons will generate it in one single line `'#include<a>#include<b>`, causing wrong config and bug
ref: https://bugs.gentoo.org/870850

fix getxattr detection by properly calling CheckFunc

---

.github/workflows/build-and-test.yml
SConstruct

Closes: #685
`echo "" | cc -xc - -c` generates a '-.o' leftover (gcc/clang).

SCons: avoid checks leftovers

---

tests/test_options/test_size.py

Before this fix, we would see
```
DeprecationWarning: invalid escape sequence '\-'
```

tests: fix "DeprecationWarning: invalid escape sequence"

---

lib/formats/json.c

as they may contain any char but \0.
Closes: #682

json: properly escape cwd and args

---

lib/formats/sh.sh

Solves "Illegal number" #679 error when two _directories_ are rechecked when generated `rmlint.sh` is executed with the `-p` parameter before removing.

Fix #679 Illegal number

---

docs/rmlint.1.rst

The documentation text begins a list with `(a)` but doesn't reference the second item with `(b)`.
This PR fixes this "semantic" typo.

(Docs) Fix semantic typo

---

docs/rmlint.1.rst

There is a simple typo I noticed in the manpage in the scripting example. The pipe is in the wrong place for the command to work.
(This is my first actual PR, please be gentle if I've made some kind of mistake!)

Fixed manpage typo in rmlint jq pipe example

---

README.rst
docs/rmlint.1.rst
docs/testing.rst
docs/translators.rst
docs/tutorial.rst

In RST, text wrapped in a \`single backtick\` is meant for "interpreted text", and is rendered using `<cite>` tags. Verbatim/literal text should instead be wrapped in \`\`double backticks\`\`, which is rendered using `<code>` tags.
See https://docutils.sourceforge.io/docs/user/rst/quickref.html#inline-markup

Fix usages of single backticks to double backticks

---

README.rst

The README page was showing maintenance from SeeSpotRun only in the range 2014-*2017*.
Leaving therefore the impression, at first glance, that this project does not have a maintainer since 2017, which apparently is not the case 
(inner .hpp files which showed dates such as 2020, etc.).
Updated maintained year to current year, 2022, so that, since the README is the first glance of a project to prospecting new users, the project will appear as currently maintained, which seems to be well the case.

Update maintainance on README to 2022. (previous: only 2017, then none)

---

SConstruct
lib/checksum.c
lib/checksums/highwayhash.c
lib/checksums/murmur3.c
lib/hash-utility.c
lib/pathtricia.c
lib/pathtricia.h
lib/replay.c
lib/xattr.c

- add a check for a truncated path (PATH_MAX is indicative only, the real maximum length of a path is file-system dependent)
- remove an unused variable
- add some static and const
- simplify header path
- add IWYU to scons

various C linting

---

tests/requirements.txt

It works well on develop without pinning at all (the day tests break, we check if that something on our side or an incompatibility from those packages).
On master, a bit more conservative strategy is to pin to major version number, that should guarantee no incompatible API changes.

tests: pin deps to current major version

---

SConstruct

SCons: fix release Python warnings

---

.github/workflows/build-and-test.yml

Skip the build test step when no executable changes are made.
This will speed up the process when only documents and such are modified. Save on quota too.
This can be improved to more fine grained step, when so desired:
* skip full build and test when only specific files are changed (global readme for instance)
* skip build and test but create man pages
* skip only test <this PR>
Adresses #690

Skip build test for non essentials #690

---

lib/checksum.c
lib/replay.c
tests/test_options/test_replay.py

Closes: #672
See bug details in https://github.com/sahib/rmlint/issues/672#issuecomment-2692483380.
This is just a bugfix, but I feel we could fix a bit more, although I'm not sure if that wouldn't introduce a regression. I haven't checked all the consumers of `file->digest`.
In `replay.c` we do:
```c
file->digest = rm_digest_new(RM_DIGEST_EXT, 0);
[...]
/* Fake the checksum using RM_DIGEST_EXT */
JsonNode *cksum_node = json_object_get_member(object, "checksum");
if(cksum_node != NULL) {
const char *cksum = json_object_get_string_member(object, "checksum");
if(cksum != NULL) {
rm_digest_update(file->digest, (unsigned char *)cksum, strlen(cksum));
}
}
```
I would do instead:
```c
file->digest = NULL;
[...]
/* Fake the checksum using RM_DIGEST_EXT */
JsonNode *cksum_node = …
```

fix data-loss issue with replays w/o checksums

---

README.rst
lib/formats/progressbar.c
lib/formats/stats.c
lib/formats/summary.c
lib/utilities.h
src/rmlint.c

Changes have been tested under SmartOS.

Add support for Solaris-based OSs

---

.github/workflows/multi-distro-build.yml

This PR adds a github-actions job that builds rmlint on several distros, mostly to check compatibility against toolchain and libraries (and avoid stalling issues like #605). 
If there is any other distro that could be added please let me know.

CI: add multi-distro build (using docker)

---

tests/test_formatters/test_sh.py

Local shell paths vary by distribution, this aims to make tests work as long as the needed shells are on the $PATH. 
It should fix some of the issues in #713 and #593.

Use proper paths for shell calls
