sahib/rmlint

src/formats/progressbar.c
Not sure why some of the lines got reformatted below; anyway the last line is the only real change.
=> Ensure progressbar goes to zero

po/fr.po
Here my new version.
Sure it's need some reviews ;)
=> Updated french version.

lib/cmdline.c, tests/test_robustness/test_manyfiles.py
=> Paranoid mem debug

lib/preprocess.c, lib/traverse.c
Fixes a couple of bugs with symlinked dirs and with path double handling
=> Symlink fix

po/fr.po
Hello sahib, here it is.
Best regards.
=> Update french translation.

lib/cmdline.c, lib/file.h, lib/hasher.c, lib/md-scheduler.c, lib/md-scheduler.h, lib/session.h, lib/shredder.c, tests/test_speed/benchmark.py, tests/test_speed/build_scripts/rmlint-spot.sh, tests/utils.py
This was a manual merge of the md-scheduler version of shredder developed in https://github.com/SeeSpotRun/rmlint/tree/scheduler.  It also contains squishes for a few potential bugs that  may have contributed to #145.
=> Scheduler clean

docs/install.rst
Cleaning is not obvious. I had to "man scons" to find how to clean.
Usually "make clean" does the job, but scons is not well known.
=> Indicate how to clean

docs/rmlint.1.rst
=> Fix formatting of unordered list in man page.

tests/test_options/test_sorting.py, tests/utils.py
Just adding a testcase to reliably reproduce the Heisenbug I was seeing
=> tests: add testcase for https://github.com/sahib/rmlint/pull/220

lib/formats/sh.c.in, lib/formats/sh.sh, tests/test_formatters/test_sh.py
=> Fix sh escape emptydirs

docs/rmlint.1.rst, lib/cmdline.c, lib/formats/sh.c.in, lib/session.c, lib/utilities.c, lib/utilities.h, src/rmlint.c, tests/test_mains/test_dedupe.py
In other words, a small tidy-up for #245
=> A couple of bugfixes, a testcase and some formatting

SConstruct, docs/install.rst, pkg/arch/PKGBUILD, pkg/fedora/rmlint.spec
Pretty trivial but saves me 5 keystrokes every build
=> SConstruct: automate choice of -j<n> (Spot got a new cpu )

lib/hasher.c, lib/shredder.c, lib/utilities.h
Fixes a few bugs discussed in #256
=> Hasher debug

lib/formats/sh.c.in, lib/formats/sh.sh
Found this handy utility (https://github.com/koalaman/shellcheck) and have conformed sh.sh/rmlint.sh accordingly
=> Shellcheck

docs/rmlint.1.rst, docs/tutorial.rst, lib/cfg.h, lib/cmdline.c, tests/test_options/test_stdin.py
Should address #273
TODO:
~~1. Documentation~~
~~2. Test case~~
=> Adds option to read null-delimited file paths from stdin

docs/rmlint.1.rst
=> Fix formatting and add cross reference

lib/utilities.c, lib/utilities.h
Fixes possible infinite loop in fiemap utilities for detecting existing file clones; fixes #299.
=> Debug #299

gui/setup.py, gui/shredder/chart.py, gui/shredder/logger.py, gui/shredder/query.py, gui/shredder/tree.py, gui/shredder/util.py, gui/shredder/views/locations.py, gui/shredder/views/settings.py
Mainly to silence syntax warnings in Python 3.8.
=> Python fixes

lib/formats/sh.sh
color_reset requires evaluating
flag error in returned flow control value
=> fix .sh output template typo

lib/preprocess.c
=> Fix regex sort

docs/install.rst
As discussed in sahib/rmlint#253 and Homebrew/homebrew-core#17434
=> clarify that mac brew install doesn't include GUI

docs/tutorial.rst
=> docs: remove unclear single-letter directory

.github/workflows/build-and-test.yml, .readthedocs.yaml, docs/requirements.txt
See: https://docs.readthedocs.com/platform/stable/config-file/index.html
@sahib hallo, do you know how to update the online documentation ? It is linked to your account, I think.
=> docs: build online documentation
